account/urls.py
from django.urls import path
from .views import *

app_name = 'account'

urlpatterns = [
    path('login/', loginAdmin, name='login'),
    path('logout/', logoutAdmin, name='logout'),
]

dashboard/urls.py
from django.urls import path

from .views import dashboard_view, get_data_jenis_kelamin, get_data_usia, get_data_output, get_data_domisili, get_data_kontak_tb, get_data_tst

app_name = 'dashboard'

urlpatterns = [
    path('', dashboard_view, name='index'),

    path('data/jenis-kelamin/', get_data_jenis_kelamin, name='data-jenis-kelamin'),
    path('data/usia/', get_data_usia, name='data-usia'),
    path('data/output/', get_data_output, name='data-output'),
    path('data/domisili/', get_data_domisili, name='data-domisili'),
    path('data/kontak-tb/', get_data_kontak_tb, name='data-kontak-tb'),
    path('data/tst/', get_data_tst, name='data-tst'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('list-pasien/', views.list_pasien, name='list_pasien'),
    path('form-pasien/', views.form_pasien, name='form_pasien'),
    path('export-excel/', views.download, name='export'),
    path('update/<str:rm_pasien>', views.update_pasien, name='edit_pasien'),
    path('delete/<str:rm_pasien>', views.delete_pasien, name='delete_pasien'),
]

tbc_abdomen_registry/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('account/', include('account.urls')),
    path('dashboard/', include('dashboard.urls')),
]

templates/base.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		
		<!-- Bootstrap CSS -->
		{% include "snippets/bootstrap-css.html" %}
		
		<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

		<!-- Block Meta -->
		{% block meta %} {% endblock meta %}
	</head>

  
  <body style="background-color: #f2f3ff;">
		<!-- Navbar -->
		{% include "navbar.html" %}

		<!-- Block Content -->
		{% block content %} {% endblock content %}

		<!-- Footer -->
		{% include "footer.html" %}

	</body>

	<!-- Bootstrap JS -->
	{% include "snippets/bootstrap-js.html" %}

	<!-- jQuery -->
	{% include "snippets/jquery.html" %}

	<!-- Block Script -->
	{% block script %}{% endblock script %}
</html>

templates/footer.html
<footer class="bg-dark text-center text-lg-start" style="padding-top: 20px; padding-bottom: 80;">

    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2); color: white;">
      Built with ❤️ by: BGN, Powered by:
      <a class="text-light" target="_blank" href="https://fuki.cs.ui.ac.id/">FUKI 2021</a>
    </div>
  </footer>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
	<div class="container">
		<a class="navbar-brand" href="{% url 'dashboard:index' %}">TBC Abdomen Registry</a>
		<button
			class="navbar-toggler"
			type="button"
			data-bs-toggle="collapse"
			data-bs-target="#navbarNav"
			aria-controls="navbarNav"
			aria-expanded="false"
			aria-label="Toggle navigation"
		>
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarNav">
			<ul class="navbar-nav ms-auto">
				<li class="nav-item">
					<a class="nav-link " href="{% url 'dashboard:index' %}">Dashboard</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'main:list_pasien' %}">List Pasien</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'main:form_pasien' %}">Register Pasien</a>
				</li>

				{% if user.is_authenticated %}
				<li class="nav-item">
					<a type="button" class="btn btn-primary ms-3"href="{% url 'account:logout' %}" >Logout</a>
				</li>			{% endif %}
			</ul>
		</div>
	</div>
</nav>