main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('list-pasien/', views.list_pasien, name='list_pasien'),
    path('form-pasien/', views.form_pasien, name='form_pasien'),
    path('export-excel/', views.download, name='export'),
    path('update/<str:rm_pasien>', views.update_pasien, name='edit_pasien'),
    path('delete/<str:rm_pasien>', views.delete_pasien, name='delete_pasien'),
]

tbc_abdomen_registry/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('account/', include('account.urls')),
    path('dashboard/', include('dashboard.urls')),
]

main/models/analisis_cairan_asites.py
from django.db import models

class AnalisisCairanAsites(models.Model):
    warna_asites = models.CharField(max_length=255, blank=True, null=True)
    rivalta_asites = models.CharField(max_length=255, blank=True, null=True)
    jumlah_sel_asites = models.CharField(max_length=255, blank=True, null=True)
    pmn_asites = models.CharField(max_length=255, blank=True, null=True)
    mn_asites = models.CharField(max_length=255, blank=True, null=True)
    glukosa_asites = models.CharField(max_length=255, blank=True, null=True)
    albumin_asites = models.CharField(max_length=255, blank=True, null=True)
    protein_asites = models.CharField(max_length=255, blank=True, null=True)
    ldh_asites = models.CharField(max_length=255, blank=True, null=True)

    def get_fields(self):
        return [(field.name, field.value_to_string(self)) for field in AnalisisCairanAsites._meta.fields]

    def get_header():
        return [(field.name) for field in AnalisisCairanAsites._meta.fields]

    def get_all_value(self):
        return [field.value_from_object(self) for field in AnalisisCairanAsites._meta.fields]

    def dict_value(self): 
        return {field.name : field.value_from_object(self) for field in AnalisisCairanAsites._meta.fields}

main/models/analisis_cairan_pleura.py
from django.db import models

class AnalisisCairanPleura(models.Model):
    warna_pleura = models.CharField(max_length=255, blank=True, null=True)
    rivalta_pleura = models.CharField(max_length=255, blank=True, null=True)
    jumlah_sel_pleura = models.CharField(max_length=255, blank=True, null=True)
    pmn_pleura = models.CharField(max_length=255, blank=True, null=True)
    mn_pleura = models.CharField(max_length=255, blank=True, null=True)
    glukosa_pleura = models.CharField(max_length=255, blank=True, null=True)
    protein_pleura = models.CharField(max_length=255, blank=True, null=True)
    albumin_pleura = models.CharField(max_length=255, blank=True, null=True)
    ldh_pleura = models.CharField(max_length=255, blank=True, null=True)

    def get_fields(self):
        return [(field.name, field.value_to_string(self)) for field in AnalisisCairanPleura._meta.fields]

    def get_header():
        return [(field.name) for field in AnalisisCairanPleura._meta.fields]

    def get_all_value(self):
        return [field.value_from_object(self) for field in AnalisisCairanPleura._meta.fields]

    def dict_value(self): 
        return {field.name : field.value_from_object(self) for field in AnalisisCairanPleura._meta.fields}

main/models/bta_sputum_aspirat_lambung.py
from django.db import models

class BtaSputumAspiratLambung(models.Model):
    POSITIF_NEGATIF_CHOICES = (("Positif", "Positif"), 
                                ("Negatif", "Negatif"))
    bta_1 = models.CharField(max_length=255, 
                                    blank=True,
                                    null=True,
                                    choices=POSITIF_NEGATIF_CHOICES)
    bta_2 = models.CharField(max_length=255, 
                                    blank=True,
                                    null=True,
                                    choices=POSITIF_NEGATIF_CHOICES)
    bta_3 = models.CharField(max_length=255, 
                                    blank=True,
                                    null=True,
                                    choices=POSITIF_NEGATIF_CHOICES)

    def get_fields(self):
        return [(field.name, field.value_to_string(self)) for field in BtaSputumAspiratLambung._meta.fields]

    def get_header():
        return [(field.name) for field in BtaSputumAspiratLambung._meta.fields]

    def get_all_value(self):
        return [field.value_from_object(self) for field in BtaSputumAspiratLambung._meta.fields]

    def dict_value(self): 
        return {field.name : field.value_from_object(self) for field in BtaSputumAspiratLambung._meta.fields}

main/models/chest_xray.py
from main.models import pembesaran_kgb
from django.db import models

class ChestXray(models.Model):
    XRAY_CHOICES = (("1", "1"), ("-", "-"))
    normal = models.CharField(max_length=255, 
                                    blank=True,
                                    null=True,
                                    choices=XRAY_CHOICES)
    klasifikasi_dengan_infiltat = models.CharField(max_length=255, 
                                    blank=True,
                                    null=True,
                                    choices=XRAY_CHOICES)
    pembesaran_kgb_hilus_atau_paratrakeal = models.CharField(max_length=255, 
                                    blank=True,
                                    null=True,
                                    choices=XRAY_CHOICES)
    kavitas = models.CharField(max_length=255, 
                                    blank=True,
                                    null=True,
                                    choices=XRAY_CHOICES)
    efusi_pleura_chest_xray = models.CharField(max_length=255, 
                                    blank=True,
                                    null=True,
                                    choices=XRAY_CHOICES)
    konsolidasi = models.CharField(max_length=255, 
                                    blank=True,
                                    null=True,
                                    choices=XRAY_CHOICES)
    milier = models.CharField(max_length=255, 
                                    blank=True,
                                    null=True,
                                    choices=XRAY_CHOICES)
    tuberkoloma = models.CharField(max_length=255, 
                                    blank=True,
                                    null=True,
                                    choices=XRAY_CHOICES)
    atelektasis = models.CharField(max_length=255, 
                                    blank=True,
                                    null=True,
                                    choices=XRAY_CHOICES)
    ekspertise = models.TextField(max_length=255, 
                                    blank=True,
                                    null=True)


    def get_fields(self):
        return [(field.name, field.value_to_string(self)) for field in ChestXray._meta.fields]

    def get_header():
        return [(field.name) for field in ChestXray._meta.fields]

    def get_all_value(self):
        return [field.value_from_object(self) for field in ChestXray._meta.fields]

    def dict_value(self): 
        return {field.name : field.value_from_object(self) for field in ChestXray._meta.fields}

main/models/diare_kronis.py
from django.db import models

class DiareKronis(models.Model):
    YA_TIDAK_CHOICES = (("Ya", "Ya"), ("Tidak", "Tidak"))
    diareKronis = models.CharField(max_length=255, 
                                    blank=True,
                                    null=True,
                                    choices=YA_TIDAK_CHOICES)
    keterangan_diare_kronis = models.TextField(blank=True, null=True)


    def get_fields(self):
        return [(field.name, field.value_to_string(self)) for field in DiareKronis._meta.fields]

    def get_header():
        return [(field.name) for field in DiareKronis._meta.fields]

    def get_all_value(self):
        return [field.value_from_object(self) for field in DiareKronis._meta.fields]

    def dict_value(self): 
        return {field.name : field.value_from_object(self) for field in DiareKronis._meta.fields}

main/models/domisili.py
from django.db import models

class Domisili(models.Model):
    bandung = models.TextField(blank=True,null=True)
    luarBandung = models.TextField(blank=True,null=True)

    def get_fields(self):
        return [(field.name, field.value_to_string(self)) for field in Domisili._meta.fields]

    def get_header():
        return [(field.name) for field in Domisili._meta.fields]

    def get_all_value(self):
        return [field.value_from_object(self) for field in Domisili._meta.fields]

    def dict_value(self): 
        return {field.name : field.value_from_object(self) for field in Domisili._meta.fields}

main/models/excel_upload.py
from django.db import models

# Create your models here.

class Pasien(models.Model):
    JENIS_KELAMIN_CHOICES = (("Laki-laki", "Laki-laki"),
                             ("Perempuan", "Perempuan"))

    rm = models.CharField(max_length=255,primary_key=True)
    tanggalPerawatan = models.DateTimeField(null=True, blank=True)
    noHp = models.CharField(max_length=255, blank=True, null=True)
    namaPasien = models.CharField(max_length=255, blank=True, null=True)
    jenis_kelamin = models.CharField(max_length=255,
                                    blank=True,
                                    null=True,
                                    choices=JENIS_KELAMIN_CHOICES)


                                    

main/models/laboratorium.py
from django.db import models

class Laboratorium(models.Model):
    hb = models.CharField(max_length=255, blank=True, null=True)
    ht = models.CharField(max_length=255, blank=True, null=True)
    leukosit = models.CharField(max_length=255, blank=True, null=True)
    trombosit = models.CharField(max_length=255, blank=True, null=True)
    basofil = models.CharField(max_length=255, blank=True, null=True)
    eosinofil = models.CharField(max_length=255, blank=True, null=True)
    n_batang = models.CharField(max_length=255, blank=True, null=True)
    n_segemen = models.CharField(max_length=255, blank=True, null=True)
    limfosit = models.CharField(max_length=255, blank=True, null=True)
    monosit = models.CharField(max_length=255, blank=True, null=True)
    sgot = models.CharField(max_length=255, blank=True, null=True)
    sgpt = models.CharField(max_length=255, blank=True, null=True)
    bil_total = models.CharField(max_length=255, blank=True, null=True)
    bil_direk = models.CharField(max_length=255, blank=True, null=True)
    albumin = models.CharField(max_length=255, blank=True, null=True)
    crp = models.CharField(max_length=255, blank=True, null=True)

    def get_fields(self):
        return [(field.name, field.value_to_string(self)) for field in Laboratorium._meta.fields]

    def get_header():
        return [(field.name) for field in Laboratorium._meta.fields]

    def get_all_value(self):
        return [field.value_from_object(self) for field in Laboratorium._meta.fields]

    def dict_value(self): 
        return {field.name : field.value_from_object(self) for field in Laboratorium._meta.fields}

main/models/luaran_saat_rawat_inap.py
from django.db import models

class LuaranSaatRawatInap(models.Model):
    LUARAN_CHOICE = (("Pulang Paksa", "Pulang Paksa"), 
    ("Perbaikan", "Perbaikan"), 
    ("Meninggal", "Meninggal"))

    status = models.CharField(max_length=255, 
                                    blank=True,
                                    null=True,
                                    choices=LUARAN_CHOICE)
    
    def get_fields(self):
        return [(field.name, field.value_to_string(self)) for field in LuaranSaatRawatInap._meta.fields]

    def get_header():
        return [(field.name) for field in LuaranSaatRawatInap._meta.fields]

    def get_all_value(self):
        return [field.value_from_object(self) for field in LuaranSaatRawatInap._meta.fields]

    def dict_value(self): 
        return {field.name : field.value_from_object(self) for field in LuaranSaatRawatInap._meta.fields}
                                    

main/models/nyeri_perut.py
from django.db import models

class NyeriPerut(models.Model):
    YA_TIDAK_CHOICES = (("Ya", "Ya"), ("Tidak", "Tidak"))
    nyeriPerut = models.CharField(max_length=255, 
                                    blank=True,
                                    null=True,
                                    choices=YA_TIDAK_CHOICES)
    keterangan_nyeri_perut = models.TextField(blank=True, null=True)

    def get_fields(self):
        return [(field.name, field.value_to_string(self)) for field in NyeriPerut._meta.fields]

    def get_header():
        return [(field.name) for field in NyeriPerut._meta.fields]

    def get_all_value(self):
        return [field.value_from_object(self) for field in NyeriPerut._meta.fields]

    def dict_value(self): 
        return {field.name : field.value_from_object(self) for field in NyeriPerut._meta.fields}

main/models/pembesaran_kgb.py
from django.db import models

class PembesaranKgb(models.Model):
    YA_TIDAK_CHOICES = (("Ya", "Ya"), ("Tidak", "Tidak"))
    pembesaran_kgb_utama = models.CharField(max_length=255, 
                                    blank=True,
                                    null=True,
                                    choices=YA_TIDAK_CHOICES)
    lokasi = models.TextField(blank=True, null=True)

    def get_fields(self):
        return [(field.name, field.value_to_string(self)) for field in PembesaranKgb._meta.fields]

    def get_header():
        return [(field.name) for field in PembesaranKgb._meta.fields]

    def get_all_value(self):
        return [field.value_from_object(self) for field in PembesaranKgb._meta.fields]

    def dict_value(self): 
        return {field.name : field.value_from_object(self) for field in PembesaranKgb._meta.fields}

main/models/pemeriksaan_abdomen.py
from django.db import models

class PemeriksaanAbdomen(models.Model):
    YA_TIDAK_CHOICES = (("Ya", "Ya"), ("Tidak", "Tidak"))

    distensi_abdomen = models.CharField(max_length=255,
                                    blank=True,
                                    null=True,
                                    choices=YA_TIDAK_CHOICES)

    asites = models.CharField(max_length=255,
                                    blank=True,
                                    null=True,
                                    choices=YA_TIDAK_CHOICES)

    hepatomegali = models.CharField(max_length=255,
                                    blank=True,
                                    null=True,
                                    choices=YA_TIDAK_CHOICES)

    hepatomegali_keterangan = models.TextField(blank=True, null=True)    

    splenomegali = models.CharField(max_length=255,
                                    blank=True,
                                    null=True,
                                    choices=YA_TIDAK_CHOICES)   
    
    splenomegali_keterangan = models.TextField(blank=True, null=True)  

    lingkar_perut_masuk = models.CharField(max_length=255,
                                    blank=True,
                                    null=True) 

    def get_fields(self):
        return [(field.name, field.value_to_string(self)) for field in PemeriksaanAbdomen._meta.fields]

    def get_header():
        return [(field.name) for field in PemeriksaanAbdomen._meta.fields]

    def get_all_value(self):
        return [field.value_from_object(self) for field in PemeriksaanAbdomen._meta.fields]

    def dict_value(self): 
        return {field.name : field.value_from_object(self) for field in PemeriksaanAbdomen._meta.fields}

main/models/pemeriksaan_toraks.py
from django.db import models

class PemeriksaanToraks(models.Model):
    PEMERIKASAAN_TORAKS_CHOICES = (("Normal", "Normal"),
                             ("Abnormal", "Abnormal"))
    
    pemeriksaan_toraks = models.CharField(max_length=255, 
                                    blank=True,
                                    null=True,
                                    choices=PEMERIKASAAN_TORAKS_CHOICES)

    deskripsi = models.TextField(blank=True, null=True)

    def get_fields(self):
        return [(field.name, field.value_to_string(self)) for field in PemeriksaanToraks._meta.fields]

    def get_header():
        return [(field.name) for field in PemeriksaanToraks._meta.fields]

    def get_all_value(self):
        return [field.value_from_object(self) for field in PemeriksaanToraks._meta.fields]

    def dict_value(self): 
        return {field.name : field.value_from_object(self) for field in PemeriksaanToraks._meta.fields}

main/models/perut_membesar.py
from django.db import models

class PerutMembesar(models.Model):
    YA_TIDAK_CHOICES = (("Ya", "Ya"), ("Tidak", "Tidak"))
    perutMembesar = models.CharField(max_length=255, 
                                    blank=True,
                                    null=True,
                                    choices=YA_TIDAK_CHOICES)
    keterangan_perut_membesar = models.TextField(blank=True, null=True)

    def get_fields(self):
        return [(field.name, field.value_to_string(self)) for field in PerutMembesar._meta.fields]

    def get_header():
        return [(field.name) for field in PerutMembesar._meta.fields]

    def get_all_value(self):
        return [field.value_from_object(self) for field in PerutMembesar._meta.fields]

    def dict_value(self): 
        return {field.name : field.value_from_object(self) for field in PerutMembesar._meta.fields}
    

main/templates/main/list-pasien.html
{% extends 'base.html' %} {% load static %} {% block meta %}{% load render_table from django_tables2 %}
<title>List Pasien</title>
{% endblock meta %} {% block content %}

<div class="container d-flex flex-row justify-content-center">
	<!-- Button trigger modal -->
	<button type="button" class="btn btn-primary me-3" data-bs-toggle="modal" data-bs-target="#exampleModal">
		Import dari Excel
	</button>
	

		
		
	
	
	
	
	<!-- Modal -->
	<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
		<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
			<h5 class="modal-title" id="exampleModalLabel">Masukan File Excel</h5>
			<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>

			<div class="modal-body">
				<form
				id="form"
				class="form-base"
				method="POST"
				enctype="multipart/form-data"
				action=""
			>
				{% csrf_token %}
				<div class="form-fields">
					{% for field in excel_upload_form %}
					<div class="field-wrapper">
						<div class="field-input">{{ field.label_tag }} {{ field }}</div>
						<div class="field-error">{{ field.errors }}</div>
						{% if field.help_text %}
						<p class="help">{{ field.help_text|safe }}</p>
						{% endif %}
					</div>
					{% endfor %}
				</div>

				<button type="button" class="btn btn-secondary mt-4" data-bs-dismiss="modal">
					Batal
				</button>
				<button id="btn-import" type="submit" class="button btn btn-primary form-submit-button mt-4">
					Import
				</button>
			</form>
			</div>
		</div> 
		</div>
	</div>
	

	<a type="button"href="{% url 'main:export' %}"  class="btn btn-primary ms-3">Export ke Excel</a>
</div>
<div class= "container mt-4 min-vh-100" style="overflow-x: auto">
	<table class="table table-info table-bordered border-dark table-striped rounded" style="border-color: dimgrey !important;">
			<tr class="table-warning table-bordered border-dark text-center">
				<th rowspan="3">No</th>
				<th rowspan="3">Action</th>
				<th rowspan="3">RM</th>
				<th rowspan="3">Tanggal Perawatan</th>
				<th rowspan="3">Nomor Telepon</th>
				<th rowspan="3">Nama Pasien</th>
				<th rowspan="2" colspan="2">Jenis Kelamin</th>
				<th rowspan="3">Rujukan dari</th>
				<th rowspan="2" colspan="2">Domisili</th>
				<th rowspan="2" colspan="4">Pendidikan</th>
				<th rowspan="2" colspan="5">Usia</th>
				<th rowspan="2" colspan="10">Status Gizi</th>
				<th rowspan="2" colspan="3">Status HIV</th>
				<th rowspan="2" colspan="3">Perut Membesar</th>
				<th rowspan="2" colspan="3">Nyeri Perut</th>
				<th rowspan="2" colspan="2">Keringat Malam</th>
				<th rowspan="2" colspan="3">Sesak Napas</th>
				<th rowspan="2" colspan="2">Edema</th>
				<th rowspan="2" colspan="2">Muntah</th>
				<th rowspan="2" colspan="2">Anoreksia</th>
				<th rowspan="2" colspan="3">Diare Kronis</th>
				<th rowspan="2" colspan="2">Hematoskezia/bleed per rektum</th>
				<th rowspan="2" colspan="3">Riwayat Panas >= 2 Minggu</th>
				<th rowspan="2" colspan="3">Riwayat Batuk >= 2 Minggu</th>
				<th rowspan="2" colspan="2">Riwayat BB sulit Naik</th>
				<th rowspan="3">Penurunan BB</th>
				<th rowspan="2" colspan="2">Malaise</th>
				<th rowspan="2" colspan="2">Riwayat Kontak TB Dewasa</th>
				<th rowspan="3" >Siapa</th>
				<th rowspan="2" colspan="2">Riwayat Imunisasi BCG</th>
				<th rowspan="2" colspan="2">Riwayat Pengobatan TB</th>
				<th rowspan="3" >Kapan Pengobatan TB Sebelumnya</th>
				<th rowspan="3" >Durasi Pengobatan TB Sebelumnya</th>
				<th rowspan="3" >Keadaan Umum</th>
				<th rowspan="2" colspan="2">Suhu</th>
				<th rowspan="2" colspan="3">Pembesaran KGB</th>
				<th rowspan="2" colspan="3">Pemeriksaan Toraks</th>
				<th rowspan="1" colspan="11">Pemeriksaan Abdomen</th>
				<th rowspan="2" colspan="2">Efusi Pleura</th>
				<th rowspan="2" colspan="2">Efusi Perikardium</th>
				<th rowspan="2" colspan="16">Laboratorium</th>
				<th rowspan="2" colspan="2">TST</th>
				<th rowspan="3" >TST (mm)</th>
				<th rowspan="2" colspan="5">USG Abdomen</th>
				<th rowspan="2" colspan="10">Chest X-Ray</th>
				<th rowspan="1" colspan="6">BTA sputum/aspirat lambung</th>
				<th rowspan="2" colspan="2">TCM Sputum/Aspirat Lambung</th>
				<th rowspan="2" colspan="2">TCM Asites</th>
				<th rowspan="2" colspan="3">TCM Pleura</th>
				<th rowspan="2" colspan="2">TCM Feses</th>
				<th rowspan="3">Kultur M.Tb</th>
				<th rowspan="3">LCS</th>
				<th rowspan="3">FNAB/PA jaringan</th>
				<th rowspan="3">CT Scan Abdomen</th>
				<th rowspan="2" colspan="9">Analisis Cairan Asites</th>
				<th rowspan="2" colspan="9">Analisis Cairan Pleura</th>
				<th rowspan="3">Diagnosis Akhir</th>
				<th rowspan="3">Diagnosis Komorbiditas</th>
				<th rowspan="3">Regimen OAT</th>
				<th rowspan="2" colspan="2">Prednison</th>
				<th rowspan="3">Efek Samping OAT yang muncul</th>
				<th rowspan="3">Regimen OAT diganti dengan</th>
				<th rowspan="3">LOS (Hari)</th>
				<th rowspan="2" colspan="3">Luaran Saat Rawat Inap</th>
				<th rowspan="3">Keterangan lain</th>
				<th rowspan="3">DDJP Utama</th>
				<th rowspan="3">Tanggal mulai OAT</th>
				<th rowspan="2" colspan="9">Bulan ke-1</th>
				<th rowspan="2" colspan="9">Bulan ke-2</th>
				<th rowspan="2" colspan="9">Bulan ke-3</th>
				<th rowspan="2" colspan="9">Bulan ke-4</th>
				<th rowspan="2" colspan="9">Bulan ke-5</th>
				<th rowspan="2" colspan="9">Bulan ke-6</th>
				<th rowspan="2" colspan="9">Bulan ke-7</th>
				<th rowspan="2" colspan="9">Bulan ke-8</th>
				<th rowspan="2" colspan="9">Bulan ke-9</th>
				<th rowspan="2" colspan="9">Bulan ke-10</th>
				<th rowspan="2" colspan="9">Bulan ke-11</th>
				<th rowspan="2" colspan="9">Bulan ke-12</th>
				<th rowspan="3">Durasi OAT</th>
				<th rowspan="3">Hasil Akhir Pengobatan</th>
			</tr>
			<tr style="text-align: center;" class="table-warning table-bordered border-dark">
				<th colspan="2">Distensi Abdomen</th>
				<th colspan="2">Asites</th>
				<th colspan="3">Hepatomegali</th>
				<th colspan="3">Splenomegali</th>	
				<th rowspan="2">Lingkar Perut Masuk</th>
				<th colspan="2">1</th>	
				<th colspan="2">2</th>		
				<th colspan="2">3</th>		
			</tr>
			<tr style="text-align: center;" class="table-warning table-bordered border-dark" >
				{% for header in headers %}
				<th>{{header}}</th>
				{% endfor %}
			</tr>
				{% for pasien in allValues %}
				<tr>
					<td>{{ forloop.counter }}</td>
						<td>
							<div class="btn-group">
							<a type="button" href="{% url 'main:edit_pasien' pasien.0 %}"  class="btn btn-info btn-block">Update</a>
							<form  method="POST" action="{% url 'main:delete_pasien' pasien.0 %}">
							{% csrf_token %}
							<button type="submit"class="btn btn-danger btn-block">Delete</button>
							</form>
							
							</div>
							
						</td>
					{% for data in pasien %}
					<td>{{data}}</td>
					{% endfor %}
				</tr>
				{% endfor %}
	</table>
</div>
<script>
	$('btn-import').on('click', function() {
	  $(this).prop('disabled', true);
  });
  </script>
{% endblock content %} 

{% block script %}
{% endblock script %}